name: Build on commit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        env:
          GOOS: windows
        run: go build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wsl-relay.exe
          path: ./wsl-relay.exe
