name: Go

on:
  release

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Init
      env:
        GOOS: windows
      run: go mod init github.com/Lexicality/wsl-relay; go mod tidy

    - name: Build
      env: 
        GOOS: windows
      run: go build -o wsl-relay


    - name: Upload to Release
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: wsl-relay.exe
        path: ./wsl-relay
        repo-token: ${{ secrets.GITHUB_TOKEN }}
